export const jobs = [
  {
    image: './images/photosnap.svg',
    company: 'Photosnap',
    title: 'Senior Frontend Developer',
    details: ['1d ago', 'Full Time', 'USA only'],
    techDetails: ['Frontend', 'Senior', 'HTML', 'CSS', 'JavaScript'],
    new: true,
    featured: true,
  },
  {
    image: './images/manage.svg',
    company: 'Manage',
    title: 'Fullstack Developer',
    details: ['1d ago', 'Part Time', 'Remote'],
    techDetails: ['Fullstack', 'Midweight', 'Python', 'React'],
    new: true,
    featured: true,
  },
  {
    image: './images/account.svg',
    company: 'Account',
    title: 'Junior Frontend Developer',
    details: ['2d ago', 'Part Time', 'USA only'],
    techDetails: ['Frontend', 'Junior', 'React', 'Sass', 'JavaScript'],
    new: true,
    featured: false,
  },
  {
    image: './images/myhome.svg',
    company: 'MyHome',
    title: 'Junior Frontend Developer',
    details: ['5d ago', 'Contract', 'USA only'],
    techDetails: ['Frontend', 'Junior', 'CSS', 'JavaScript'],
    new: false,
    featured: false,
  },
  {
    image: './images/loop-studios.svg',
    company: 'Loop Studios',
    title: 'Software Engineer',
    details: ['1w ago', 'Full Time', 'Worldwide'],
    techDetails: ['Fullstack', 'Midweight', 'JavaScript', 'Sass', 'Ruby'],
    new: false,
    featured: false,
  },
  {
    image: './images/faceit.svg',
    company: 'FaceIt',
    title: 'Junior Backend Developer',
    details: ['2w ago', 'Full Time', 'UK only'],
    techDetails: ['Backend', 'Junior', 'Ruby', 'RoR'],
    new: false,
    featured: false,
  },
  {
    image: './images/shortly.svg',
    company: 'Shortly',
    title: 'Junior Developer',
    details: ['2w ago', 'Full Time', 'Worldwide'],
    techDetails: ['Frontend', 'Junior', 'HTML', 'Sass', 'JavaScript'],
    new: false,
    featured: false,
  },
  {
    image: './images/insure.svg',
    company: 'Insure',
    title: 'Junior Frontend Developer',
    details: ['2w ago', 'Full Time', 'USA only'],
    techDetails: ['Frontend', 'Junior', 'Vue', 'JavaScript', 'Sass'],
    new: false,
    featured: false,
  },
  {
    image: './images/eyecam-co.svg',
    company: 'Eyecam Co.',
    title: 'Full Stack Engineer',
    details: ['3w ago', 'Full Time', 'Worldwide'],
    techDetails: ['Fullstack', 'Midweight', 'JavaScript', 'Django', 'Python'],
    new: false,
    featured: false,
  },
  {
    image: './images/the-air-filter-company.svg',
    company: 'The Air Filter Company',
    title: 'Front-end Dev',
    details: ['1m ago', 'Full Time', 'Worldwide'],
    techDetails: ['Frontend', 'Junior', 'React', 'Sass', 'JavaScript'],
    new: false,
    featured: false,
  },
]
